# Generated by Django 5.0.3 on 2024-03-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_Image', models.ImageField(upload_to='images/')),
                ('profile_Summary', models.CharField(max_length=200)),
            ],
        ),
    ]
