# Generated by Django 5.0.3 on 2024-03-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='profile_Summary',
            field=models.CharField(max_length=800),
        ),
    ]
