# Generated by Django 5.0.3 on 2024-03-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_profile_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='profile_Image',
            new_name='profileImage',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='profile_Summary',
            new_name='profileSummary',
        ),
        migrations.AddField(
            model_name='job',
            name='profileDescription',
            field=models.CharField(default='', max_length=200),
        ),
    ]
