# Generated by Django 5.0.3 on 2024-03-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_profile_image_job_profileimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='profileDescription',
            new_name='jobDescription',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='profileImage',
            new_name='jobImage',
        ),
        migrations.RemoveField(
            model_name='job',
            name='profileSummary',
        ),
        migrations.AddField(
            model_name='job',
            name='jobSummary',
            field=models.CharField(default='', max_length=800),
        ),
    ]
