# Generated by Django 5.0.3 on 2024-03-22 01:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_profiledescription_job_jobdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(default='Enter your name in DB', max_length=20)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.CharField(choices=[('OpenToWork', 'OpenToWork'), ('CurrentlyWorking', 'Currently Working'), ('ST', 'Student'), ('WK', 'Working'), ('FL', 'Freelance'), ('LO', 'Looking for Opportunity')], default='Open To Work', max_length=50)),
                ('currentStatus', models.CharField(choices=[('OpenToWork', 'OpenToWork'), ('CurrentlyWorking', 'Currently Working'), ('ST', 'Student'), ('WK', 'Working'), ('FL', 'Freelance'), ('LO', 'Looking for Opportunity')], default='Looking for Opportunity', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='date_of_joining',
            field=models.DateField(default=None),
        ),
    ]
