# Generated by Django 5.0.3 on 2024-03-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_jobdescription_alter_job_jobsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_of_joining',
            field=models.DateField(default=''),
        ),
    ]
