# Generated by Django 5.0.3 on 2024-03-22 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_of_joining',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
