# Generated by Django 5.0.3 on 2024-03-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_date_of_joining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_of_joining',
        ),
    ]
