# Generated by Django 5.0.3 on 2024-04-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_job_date_of_joining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='about',
            name='status',
        ),
    ]
