# Generated by Django 5.0.3 on 2024-04-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_about_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Degree',
            field=models.CharField(default='Masters in Computer Applications', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='city',
            field=models.CharField(default='Saint John', max_length=200),
        ),
    ]
