# Generated by Django 5.0.3 on 2024-04-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_rename_degree_about_degree_alter_about_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Roles',
            field=models.CharField(default='Web Developer & Freelancer', max_length=100),
        ),
    ]
