# Generated by Django 5.0.3 on 2024-04-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_about_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Roles',
            new_name='roles',
        ),
    ]
