# Generated by Django 5.0.3 on 2024-04-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_rename_roles_about_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
