# Generated by Django 5.0.3 on 2024-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_about_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='experience',
            field=models.IntegerField(default=3),
        ),
    ]
