# Generated by Django 5.0.3 on 2024-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_about_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_about2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
