# Generated by Django 5.0.3 on 2024-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_about_profile_about2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
